# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Konstantinos Metaxas"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "deadoralive1908@ionio.gr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "6935557334"
resume_contact_address:         "18 Καραϊσκάκη, Αθήνα"

resume_header_contact_info:     "18 Καραϊσκάκη, Αθήνα, Springfield • 6935557334 • deadoralive1908@ionio.gr"
display_header_contact_info:    "false"

resume_header_intro: "<p>Τελειόφοιτος πληροφορικής με έφεση στη κατασκευή προσωποποιημένων λειτουργικών συστημάτων και εφαρμογών ιστοσελίδων.
Στόχος μου είναι να ξεπερνώ τις προσδοκίες με σκληρή δουλειά, ομαδικότητα αλλά και προσοχή στη λεπτομέρεια.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/deadoralive1908/konstantinos-cv-jekyll-theme"
  resume_twitter_url:           "http://twitter.com/km"
  resume_dribbble_url:          "https://dribbble.com/km"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/km"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@km"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
